const scoreboard = [
  {
    id: 401752708,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: "ABC",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Simmons Bank Liberty Stadium",
      city: "Memphis",
      state: "TN",
    },
    homeTeam: {
      id: 235,
      name: "Memphis Tigers",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 8,
      name: "Arkansas Razorbacks",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 83.1,
      description: null,
      windSpeed: 5.8,
      windDirection: 110,
    },
    betting: {
      spread: 7.5,
      overUnder: 63,
      homeMoneyline: 195,
      awayMoneyline: -235,
    },
  },
  {
    id: 401752709,
    startDate: "2025-09-20T23:30:00.000Z",
    startTimeTBD: false,
    tv: "ABC",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Hard Rock Stadium",
      city: "Miami Gardens",
      state: "FL",
    },
    homeTeam: {
      id: 2390,
      name: "Miami Hurricanes",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 57,
      name: "Florida Gators",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 82.2,
      description: "Light Rain",
      windSpeed: 8.1,
      windDirection: 99,
    },
    betting: {
      spread: -7.5,
      overUnder: 51,
      homeMoneyline: -290,
      awayMoneyline: 240,
    },
  },
  {
    id: 401752710,
    startDate: "2025-09-20T23:45:00.000Z",
    startTimeTBD: false,
    tv: "SEC Network",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Tiger Stadium (LA)",
      city: "Baton Rouge",
      state: "LA",
    },
    homeTeam: {
      id: 99,
      name: "LSU Tigers",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2545,
      name: "SE Louisiana Lions",
      conference: "Southland",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 72,
      description: null,
      windSpeed: 5.8,
      windDirection: 53,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401752711,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: "ESPN",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Vaught-Hemingway Stadium",
      city: "Oxford",
      state: "MS",
    },
    homeTeam: {
      id: 145,
      name: "Ole Miss Rebels",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2655,
      name: "Tulane Green Wave",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 72.1,
      description: null,
      windSpeed: 6.7,
      windDirection: 122,
    },
    betting: {
      spread: -12,
      overUnder: 61,
      homeMoneyline: -470,
      awayMoneyline: 345,
    },
  },
  {
    id: 401752712,
    startDate: "2025-09-20T20:15:00.000Z",
    startTimeTBD: false,
    tv: "SEC Network",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Davis Wade Stadium",
      city: "Starkville",
      state: "MS",
    },
    homeTeam: {
      id: 344,
      name: "Mississippi State Bulldogs",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2459,
      name: "Northern Illinois Huskies",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 87.1,
      description: null,
      windSpeed: 0.2,
      windDirection: 199,
    },
    betting: {
      spread: -21,
      overUnder: 50,
      homeMoneyline: -1900,
      awayMoneyline: 900,
    },
  },
  {
    id: 401752713,
    startDate: "2025-09-20T23:00:00.000Z",
    startTimeTBD: false,
    tv: "ESPN",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Memorial Stadium",
      city: "Columbia",
      state: "MO",
    },
    homeTeam: {
      id: 142,
      name: "Missouri Tigers",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2579,
      name: "South Carolina Gamecocks",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 68.5,
      description: null,
      windSpeed: 4.9,
      windDirection: 158,
    },
    betting: {
      spread: -13.5,
      overUnder: 47,
      homeMoneyline: -550,
      awayMoneyline: 390,
    },
  },
  {
    id: 401752714,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: "ABC",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Memorial Stadium (Norman, OK)",
      city: "Norman",
      state: "OK",
    },
    homeTeam: {
      id: 201,
      name: "Oklahoma Sooners",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2,
      name: "Auburn Tigers",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 88,
      description: null,
      windSpeed: 10.4,
      windDirection: 158,
    },
    betting: {
      spread: -6.5,
      overUnder: 47.5,
      homeMoneyline: -240,
      awayMoneyline: 200,
    },
  },
  {
    id: 401752715,
    startDate: "2025-09-20T16:45:00.000Z",
    startTimeTBD: false,
    tv: "SEC Network",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Neyland Stadium",
      city: "Knoxville",
      state: "TN",
    },
    homeTeam: {
      id: 2633,
      name: "Tennessee Volunteers",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 5,
      name: "UAB Blazers",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 69.3,
      description: null,
      windSpeed: 2,
      windDirection: 69,
    },
    betting: {
      spread: -40,
      overUnder: 69,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401752716,
    startDate: "2025-09-20T23:30:00.000Z",
    startTimeTBD: false,
    tv: "ESPNU",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "FirstBank Stadium",
      city: "Nashville",
      state: "TN",
    },
    homeTeam: {
      id: 238,
      name: "Vanderbilt Commodores",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2247,
      name: "Georgia State Panthers",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 79.7,
      description: null,
      windSpeed: 5.8,
      windDirection: 58,
    },
    betting: {
      spread: -26.5,
      overUnder: 53.5,
      homeMoneyline: -5000,
      awayMoneyline: 1300,
    },
  },
  {
    id: 401752723,
    startDate: "2025-09-21T00:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "DKR-Texas Memorial Stadium",
      city: "Austin",
      state: "TX",
    },
    homeTeam: {
      id: 251,
      name: "Texas Longhorns",
      conference: "SEC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2534,
      name: "Sam Houston Bearkats",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 86,
      description: null,
      windSpeed: 4.6,
      windDirection: 115,
    },
    betting: {
      spread: -41,
      overUnder: 51.5,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401752841,
    startDate: "2025-09-20T19:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Autzen Stadium",
      city: "Eugene",
      state: "OR",
    },
    homeTeam: {
      id: 2483,
      name: "Oregon Ducks",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 204,
      name: "Oregon State Beavers",
      conference: "Pac-12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 52.3,
      description: null,
      windSpeed: 1.8,
      windDirection: 87,
    },
    betting: {
      spread: -35,
      overUnder: 55.5,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401752842,
    startDate: "2025-09-20T23:30:00.000Z",
    startTimeTBD: false,
    tv: "CBS",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Gesa Field",
      city: "Pullman",
      state: "WA",
    },
    homeTeam: {
      id: 265,
      name: "Washington State Cougars",
      conference: "Pac-12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 264,
      name: "Washington Huskies",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 64.8,
      description: null,
      windSpeed: 6.5,
      windDirection: 41,
    },
    betting: {
      spread: 20,
      overUnder: 52,
      homeMoneyline: 750,
      awayMoneyline: -1400,
    },
  },
  {
    id: 401752843,
    startDate: "2025-09-20T23:30:00.000Z",
    startTimeTBD: false,
    tv: "NBC",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Memorial Stadium (Bloomington, IN)",
      city: "Bloomington",
      state: "IN",
    },
    homeTeam: {
      id: 84,
      name: "Indiana Hoosiers",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 356,
      name: "Illinois Fighting Illini",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 73.2,
      description: null,
      windSpeed: 2.7,
      windDirection: 99,
    },
    betting: {
      spread: -4.5,
      overUnder: 52.5,
      homeMoneyline: -210,
      awayMoneyline: 175,
    },
  },
  {
    id: 401752844,
    startDate: "2025-09-20T00:00:00.000Z",
    startTimeTBD: false,
    tv: "FOX",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "SHI Stadium",
      city: "Piscataway",
      state: "NJ",
    },
    homeTeam: {
      id: 164,
      name: "Rutgers Scarlet Knights",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2294,
      name: "Iowa Hawkeyes",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 68,
      description: null,
      windSpeed: 3.6,
      windDirection: 130,
    },
    betting: {
      spread: 3,
      overUnder: 45.5,
      homeMoneyline: 105,
      awayMoneyline: -125,
    },
  },
  {
    id: 401752845,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Camp Randall Stadium",
      city: "Madison",
      state: "WI",
    },
    homeTeam: {
      id: 275,
      name: "Wisconsin Badgers",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 120,
      name: "Maryland Terrapins",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 64.8,
      description: null,
      windSpeed: 3.8,
      windDirection: 122,
    },
    betting: {
      spread: -10,
      overUnder: 43.5,
      homeMoneyline: -320,
      awayMoneyline: 260,
    },
  },
  {
    id: 401752846,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: "CBS",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Memorial Stadium (Lincoln, NE)",
      city: "Lincoln",
      state: "NE",
    },
    homeTeam: {
      id: 158,
      name: "Nebraska Cornhuskers",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 130,
      name: "Michigan Wolverines",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 69.6,
      description: null,
      windSpeed: 10.5,
      windDirection: 164,
    },
    betting: {
      spread: 2.5,
      overUnder: 46,
      homeMoneyline: 105,
      awayMoneyline: -125,
    },
  },
  {
    id: 401752847,
    startDate: "2025-09-21T03:00:00.000Z",
    startTimeTBD: false,
    tv: "FOX",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Los Angeles Memorial Coliseum",
      city: "Los Angeles",
      state: "CA",
    },
    homeTeam: {
      id: 30,
      name: "USC Trojans",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 127,
      name: "Michigan State Spartans",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 71.6,
      description: null,
      windSpeed: 8.1,
      windDirection: 244,
    },
    betting: {
      spread: -17.5,
      overUnder: 55.5,
      homeMoneyline: -700,
      awayMoneyline: 475,
    },
  },
  {
    id: 401752848,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: "NBC",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Notre Dame Stadium",
      city: "Notre Dame",
      state: "IN",
    },
    homeTeam: {
      id: 87,
      name: "Notre Dame Fighting Irish",
      conference: "FBS Independents",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2509,
      name: "Purdue Boilermakers",
      conference: "Big Ten",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 65.8,
      description: null,
      windSpeed: 3.4,
      windDirection: 109,
    },
    betting: {
      spread: -27,
      overUnder: 55,
      homeMoneyline: -5000,
      awayMoneyline: 1300,
    },
  },
  {
    id: 401754537,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: "ESPN",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Memorial Stadium (Clemson, SC)",
      city: "Clemson",
      state: "SC",
    },
    homeTeam: {
      id: 228,
      name: "Clemson Tigers",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 183,
      name: "Syracuse Orange",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 67.3,
      description: null,
      windSpeed: 5.8,
      windDirection: 45,
    },
    betting: {
      spread: -17,
      overUnder: 55,
      homeMoneyline: -850,
      awayMoneyline: 550,
    },
  },
  {
    id: 401754538,
    startDate: "2025-09-20T20:00:00.000Z",
    startTimeTBD: false,
    tv: "ESPN2",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Wallace Wade Stadium",
      city: "Durham",
      state: "NC",
    },
    homeTeam: {
      id: 150,
      name: "Duke Blue Devils",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 152,
      name: "NC State Wolfpack",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 79.5,
      description: null,
      windSpeed: 6.9,
      windDirection: 86,
    },
    betting: {
      spread: -3,
      overUnder: 59,
      homeMoneyline: -130,
      awayMoneyline: 110,
    },
  },
  {
    id: 401754539,
    startDate: "2025-09-20T23:30:00.000Z",
    startTimeTBD: false,
    tv: "ACC Network",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Scott Stadium",
      city: "Charlottesville",
      state: "VA",
    },
    homeTeam: {
      id: 258,
      name: "Virginia Cavaliers",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 24,
      name: "Stanford Cardinal",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 64.2,
      description: null,
      windSpeed: 4,
      windDirection: 17,
    },
    betting: {
      spread: -15.5,
      overUnder: 49,
      homeMoneyline: -800,
      awayMoneyline: 525,
    },
  },
  {
    id: 401754540,
    startDate: "2025-09-21T02:30:00.000Z",
    startTimeTBD: false,
    tv: "CBSSN",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Snapdragon Stadium",
      city: "San Diego",
      state: "CA",
    },
    homeTeam: {
      id: 21,
      name: "San Diego State Aztecs",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 25,
      name: "California Golden Bears",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 73,
      description: null,
      windSpeed: 5.8,
      windDirection: 285,
    },
    betting: {
      spread: 13,
      overUnder: 48.5,
      homeMoneyline: 370,
      awayMoneyline: -510,
    },
  },
  {
    id: 401754541,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: "ACC Network",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Doak Campbell Stadium",
      city: "Tallahassee",
      state: "FL",
    },
    homeTeam: {
      id: 52,
      name: "Florida State Seminoles",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2309,
      name: "Kent State Golden Flashes",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 85.5,
      description: null,
      windSpeed: 8.1,
      windDirection: 73,
    },
    betting: {
      spread: -44.5,
      overUnder: 55.5,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401754542,
    startDate: "2025-09-20T20:30:00.000Z",
    startTimeTBD: false,
    tv: "The CW Network",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Bobby Dodd Stadium",
      city: "Atlanta",
      state: "GA",
    },
    homeTeam: {
      id: 59,
      name: "Georgia Tech Yellow Jackets",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 218,
      name: "Temple Owls",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 79.2,
      description: null,
      windSpeed: 6.9,
      windDirection: 42,
    },
    betting: {
      spread: -24,
      overUnder: 53,
      homeMoneyline: -2500,
      awayMoneyline: 1000,
    },
  },
  {
    id: 401754617,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Lane Stadium",
      city: "Blacksburg",
      state: "VA",
    },
    homeTeam: {
      id: 259,
      name: "Virginia Tech Hokies",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2747,
      name: "Wofford Terriers",
      conference: "Southern",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 62.1,
      description: null,
      windSpeed: 4.2,
      windDirection: 90,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401754636,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: "ESPN",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Amon G. Carter Stadium",
      city: "Fort Worth",
      state: "TX",
    },
    homeTeam: {
      id: 2628,
      name: "TCU Horned Frogs",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2567,
      name: "SMU Mustangs",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 73,
      description: null,
      windSpeed: 4.5,
      windDirection: 135,
    },
    betting: {
      spread: -7,
      overUnder: 64,
      homeMoneyline: -245,
      awayMoneyline: 205,
    },
  },
  {
    id: 401754636,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: "ESPN2",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Amon G. Carter Stadium",
      city: "Fort Worth",
      state: "TX",
    },
    homeTeam: {
      id: 2628,
      name: "TCU Horned Frogs",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2567,
      name: "SMU Mustangs",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 73,
      description: null,
      windSpeed: 4.5,
      windDirection: 135,
    },
    betting: {
      spread: -7,
      overUnder: 64,
      homeMoneyline: -245,
      awayMoneyline: 205,
    },
  },
  {
    id: 401754640,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: "FOX",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "FBC Mortgage Stadium",
      city: "Orlando",
      state: "FL",
    },
    homeTeam: {
      id: 2116,
      name: "UCF Knights",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 153,
      name: "North Carolina Tar Heels",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 84.4,
      description: null,
      windSpeed: 10.4,
      windDirection: 81,
    },
    betting: {
      spread: -6.5,
      overUnder: 49,
      homeMoneyline: -240,
      awayMoneyline: 200,
    },
  },
  {
    id: 401754642,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: "ACC Network",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "L&N Federal Credit Union Stadium",
      city: "Louisville",
      state: "KY",
    },
    homeTeam: {
      id: 97,
      name: "Louisville Cardinals",
      conference: "ACC",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 189,
      name: "Bowling Green Falcons",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 80.1,
      description: null,
      windSpeed: 6.9,
      windDirection: 30,
    },
    betting: {
      spread: -26.5,
      overUnder: 51.5,
      homeMoneyline: -6500,
      awayMoneyline: 1300,
    },
  },
  {
    id: 401756896,
    startDate: "2025-09-20T23:30:00.000Z",
    startTimeTBD: false,
    tv: "FOX",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "McLane Stadium",
      city: "Waco",
      state: "TX",
    },
    homeTeam: {
      id: 239,
      name: "Baylor Bears",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 9,
      name: "Arizona State Sun Devils",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 70.9,
      description: null,
      windSpeed: 4.9,
      windDirection: 107,
    },
    betting: {
      spread: -2,
      overUnder: 60.5,
      homeMoneyline: -130,
      awayMoneyline: 110,
    },
  },
  {
    id: 401756897,
    startDate: "2025-09-21T02:15:00.000Z",
    startTimeTBD: false,
    tv: "ESPN",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Folsom Field",
      city: "Boulder",
      state: "CO",
    },
    homeTeam: {
      id: 38,
      name: "Colorado Buffaloes",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2751,
      name: "Wyoming Cowboys",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: null,
      description: null,
      windSpeed: null,
      windDirection: null,
    },
    betting: {
      spread: -13.5,
      overUnder: 44.5,
      homeMoneyline: -550,
      awayMoneyline: 390,
    },
  },
  {
    id: 401756898,
    startDate: "2025-09-20T23:30:00.000Z",
    startTimeTBD: false,
    tv: "ESPN2",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Dowdy-Ficklen Stadium",
      city: "Greenville",
      state: "NC",
    },
    homeTeam: {
      id: 151,
      name: "East Carolina Pirates",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 252,
      name: "BYU Cougars",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 65.8,
      description: null,
      windSpeed: 7.8,
      windDirection: 12,
    },
    betting: {
      spread: 7.5,
      overUnder: 49.5,
      homeMoneyline: 195,
      awayMoneyline: -235,
    },
  },
  {
    id: 401756899,
    startDate: "2025-09-20T22:00:00.000Z",
    startTimeTBD: false,
    tv: "FS1",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Memorial Stadium",
      city: "Lawrence",
      state: "KS",
    },
    homeTeam: {
      id: 2305,
      name: "Kansas Jayhawks",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 277,
      name: "West Virginia Mountaineers",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 79.7,
      description: null,
      windSpeed: 6.3,
      windDirection: 178,
    },
    betting: {
      spread: -13.5,
      overUnder: 54.5,
      homeMoneyline: -460,
      awayMoneyline: 340,
    },
  },
  {
    id: 401756900,
    startDate: "2025-09-19T23:30:00.000Z",
    startTimeTBD: false,
    tv: "ESPN",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Boone Pickens Stadium",
      city: "Stillwater",
      state: "OK",
    },
    homeTeam: {
      id: 197,
      name: "Oklahoma State Cowboys",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 202,
      name: "Tulsa Golden Hurricane",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 87.1,
      description: null,
      windSpeed: 10.5,
      windDirection: 164,
    },
    betting: {
      spread: -13,
      overUnder: 54.5,
      homeMoneyline: -510,
      awayMoneyline: 370,
    },
  },
  {
    id: 401756901,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: "FOX",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Rice-Eccles Stadium",
      city: "Salt Lake City",
      state: "UT",
    },
    homeTeam: {
      id: 254,
      name: "Utah Utes",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2641,
      name: "Texas Tech Red Raiders",
      conference: "Big 12",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 68.2,
      description: null,
      windSpeed: 9.2,
      windDirection: 130,
    },
    betting: {
      spread: -3,
      overUnder: 57.5,
      homeMoneyline: -175,
      awayMoneyline: 150,
    },
  },
  {
    id: 401757169,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: "CBSSN",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Pratt & Whitney Stadium",
      city: "East Hartford",
      state: "CT",
    },
    homeTeam: {
      id: 41,
      name: "UConn Huskies",
      conference: "FBS Independents",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2050,
      name: "Ball State Cardinals",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 59.5,
      description: null,
      windSpeed: 2.5,
      windDirection: 8,
    },
    betting: {
      spread: -21,
      overUnder: 52.5,
      homeMoneyline: -1400,
      awayMoneyline: 750,
    },
  },
  {
    id: 401757259,
    startDate: "2025-09-20T22:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Pitbull Stadium",
      city: "Miami",
      state: "FL",
    },
    homeTeam: {
      id: 2229,
      name: "Florida International Panthers",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 48,
      name: "Delaware Blue Hens",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: null,
      description: null,
      windSpeed: null,
      windDirection: null,
    },
    betting: {
      spread: -6,
      overUnder: 55,
      homeMoneyline: -200,
      awayMoneyline: 170,
    },
  },
  {
    id: 401757260,
    startDate: "2025-09-20T23:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "AmFirst Stadium",
      city: "Jacksonville",
      state: "AL",
    },
    homeTeam: {
      id: 55,
      name: "Jacksonville State Gamecocks",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 93,
      name: "Murray State Racers",
      conference: "MVFC",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 68.4,
      description: null,
      windSpeed: 6.5,
      windDirection: 97,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401757261,
    startDate: "2025-09-20T22:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Fifth Third Stadium",
      city: "Kennesaw",
      state: "GA",
    },
    homeTeam: {
      id: 338,
      name: "Kennesaw State Owls",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2032,
      name: "Arkansas State Red Wolves",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 68.5,
      description: null,
      windSpeed: 5.6,
      windDirection: 70,
    },
    betting: {
      spread: 6,
      overUnder: 56.5,
      homeMoneyline: 210,
      awayMoneyline: -250,
    },
  },
  {
    id: 401757262,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: "ESPNU",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Williams Stadium (VA)",
      city: "Lynchburg",
      state: "VA",
    },
    homeTeam: {
      id: 2335,
      name: "Liberty Flames",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 256,
      name: "James Madison Dukes",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 63.5,
      description: null,
      windSpeed: 5.8,
      windDirection: 45,
    },
    betting: {
      spread: 9.5,
      overUnder: 49,
      homeMoneyline: 290,
      awayMoneyline: -380,
    },
  },
  {
    id: 401757263,
    startDate: "2025-09-20T23:30:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Joe Aillet Stadium",
      city: "Ruston",
      state: "LA",
    },
    homeTeam: {
      id: 2348,
      name: "Louisiana Tech Bulldogs",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2572,
      name: "Southern Miss Golden Eagles",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 69.3,
      description: null,
      windSpeed: 5.2,
      windDirection: 59,
    },
    betting: {
      spread: -3,
      overUnder: 51,
      homeMoneyline: -145,
      awayMoneyline: 125,
    },
  },
  {
    id: 401757264,
    startDate: "2025-09-20T23:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: 'Johnny "Red" Floyd Stadium',
      city: "Murfreesboro",
      state: "TN",
    },
    homeTeam: {
      id: 2393,
      name: "Middle Tennessee Blue Raiders",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 276,
      name: "Marshall Thundering Herd",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 72.1,
      description: null,
      windSpeed: 2.7,
      windDirection: 172,
    },
    betting: {
      spread: 2.5,
      overUnder: 47.5,
      homeMoneyline: 115,
      awayMoneyline: -135,
    },
  },
  {
    id: 401757265,
    startDate: "2025-09-20T23:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Plaster Sports Complex",
      city: "Springfield",
      state: "MO",
    },
    homeTeam: {
      id: 2623,
      name: "Missouri State Bears",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2630,
      name: "UT Martin Skyhawks",
      conference: "Big South-OVC",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 76.3,
      description: null,
      windSpeed: 5.3,
      windDirection: 123,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401757267,
    startDate: "2025-09-21T01:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Sun Bowl",
      city: "El Paso",
      state: "TX",
    },
    homeTeam: {
      id: 2638,
      name: "UTEP Miners",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2433,
      name: "UL Monroe Warhawks",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 83.7,
      description: "Rain",
      windSpeed: 9.2,
      windDirection: 129,
    },
    betting: {
      spread: -5.5,
      overUnder: 47,
      homeMoneyline: -220,
      awayMoneyline: 180,
    },
  },
  {
    id: 401757268,
    startDate: "2025-09-20T23:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Houchens Industries-L.T. Smith Stadium",
      city: "Bowling Green",
      state: "KY",
    },
    homeTeam: {
      id: 98,
      name: "Western Kentucky Hilltoppers",
      conference: "Conference USA",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2440,
      name: "Nevada Wolf Pack",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 71.6,
      description: null,
      windSpeed: 3.4,
      windDirection: 149,
    },
    betting: {
      spread: -10.5,
      overUnder: 55,
      homeMoneyline: -430,
      awayMoneyline: 320,
    },
  },
  {
    id: 401760372,
    startDate: "2025-09-20T23:00:00.000Z",
    startTimeTBD: false,
    tv: "CBSSN",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Falcon Stadium",
      city: "Colorado Springs",
      state: "CO",
    },
    homeTeam: {
      id: 2005,
      name: "Air Force Falcons",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 68,
      name: "Boise State Broncos",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 80.2,
      description: null,
      windSpeed: 6.9,
      windDirection: 212,
    },
    betting: {
      spread: 10,
      overUnder: 51.5,
      homeMoneyline: 275,
      awayMoneyline: -350,
    },
  },
  {
    id: 401760373,
    startDate: "2025-09-21T01:30:00.000Z",
    startTimeTBD: false,
    tv: "FS1",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Canvas Stadium",
      city: "Fort Collins",
      state: "CO",
    },
    homeTeam: {
      id: 36,
      name: "Colorado State Rams",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2636,
      name: "UTSA Roadrunners",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 60.3,
      description: null,
      windSpeed: 4.7,
      windDirection: 333,
    },
    betting: {
      spread: 4.5,
      overUnder: 59.5,
      homeMoneyline: 160,
      awayMoneyline: -185,
    },
  },
  {
    id: 401760374,
    startDate: "2025-09-21T03:59:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Clarence T.C. Ching Athletics Complex",
      city: "Honolulu",
      state: "HI",
    },
    homeTeam: {
      id: 62,
      name: "Hawai'i Rainbow Warriors",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 278,
      name: "Fresno State Bulldogs",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 80.4,
      description: "Fair",
      windSpeed: 10.4,
      windDirection: 61,
    },
    betting: {
      spread: 3,
      overUnder: 47.5,
      homeMoneyline: 145,
      awayMoneyline: -170,
    },
  },
  {
    id: 401760375,
    startDate: "2025-09-20T21:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "CEFCU Stadium",
      city: "San Jose",
      state: "CA",
    },
    homeTeam: {
      id: 23,
      name: "San José State Spartans",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 70,
      name: "Idaho Vandals",
      conference: "Big Sky",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 69.8,
      description: null,
      windSpeed: 0.4,
      windDirection: 61,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401760376,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: "ESPNU",
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Yager Stadium",
      city: "Oxford",
      state: "OH",
    },
    homeTeam: {
      id: 193,
      name: "Miami (OH) RedHawks",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2439,
      name: "UNLV Rebels",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 66.9,
      description: null,
      windSpeed: 2,
      windDirection: 69,
    },
    betting: {
      spread: 2.5,
      overUnder: 48,
      homeMoneyline: 145,
      awayMoneyline: -170,
    },
  },
  {
    id: 401760377,
    startDate: "2025-09-21T00:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Maverik Stadium",
      city: "Logan",
      state: "UT",
    },
    homeTeam: {
      id: 328,
      name: "Utah State Aggies",
      conference: "Mountain West",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2377,
      name: "McNeese Cowboys",
      conference: "Southland",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 48.6,
      description: null,
      windSpeed: 2.5,
      windDirection: 135,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401761609,
    startDate: "2025-09-20T23:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Allen E. Paulson Stadium",
      city: "Statesboro",
      state: "GA",
    },
    homeTeam: {
      id: 290,
      name: "Georgia Southern Eagles",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 311,
      name: "Maine Black Bears",
      conference: "CAA",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 70.2,
      description: null,
      windSpeed: 8.7,
      windDirection: 55,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401761610,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Rynearson Stadium",
      city: "Ypsilanti",
      state: "MI",
    },
    homeTeam: {
      id: 2199,
      name: "Eastern Michigan Eagles",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 309,
      name: "Louisiana Ragin' Cajuns",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 66,
      description: null,
      windSpeed: 2,
      windDirection: 322,
    },
    betting: {
      spread: 2.5,
      overUnder: 51.5,
      homeMoneyline: 140,
      awayMoneyline: -165,
    },
  },
  {
    id: 401761611,
    startDate: "2025-09-20T23:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Hancock Whitney Stadium",
      city: "Mobile",
      state: "AL",
    },
    homeTeam: {
      id: 6,
      name: "South Alabama Jaguars",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 324,
      name: "Coastal Carolina Chanticleers",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 80.1,
      description: null,
      windSpeed: 8.1,
      windDirection: 62,
    },
    betting: {
      spread: -14.5,
      overUnder: 50.5,
      homeMoneyline: -625,
      awayMoneyline: 430,
    },
  },
  {
    id: 401761612,
    startDate: "2025-09-21T00:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Bobcat Stadium (TX)",
      city: "San Marcos",
      state: "TX",
    },
    homeTeam: {
      id: 326,
      name: "Texas State Bobcats",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2447,
      name: "Nicholls Colonels",
      conference: "Southland",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: null,
      description: null,
      windSpeed: null,
      windDirection: null,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401761613,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "UB Stadium",
      city: "Amherst",
      state: "NY",
    },
    homeTeam: {
      id: 2084,
      name: "Buffalo Bulls",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2653,
      name: "Troy Trojans",
      conference: "Sun Belt",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 74.3,
      description: "Cloudy",
      windSpeed: 10.4,
      windDirection: 131,
    },
    betting: {
      spread: -5.5,
      overUnder: 42.5,
      homeMoneyline: -230,
      awayMoneyline: 190,
    },
  },
  {
    id: 401762468,
    startDate: "2025-09-18T23:30:00.000Z",
    startTimeTBD: false,
    tv: "ESPN",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Jerry Richardson Stadium",
      city: "Charlotte",
      state: "NC",
    },
    homeTeam: {
      id: 2429,
      name: "Charlotte 49ers",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 242,
      name: "Rice Owls",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 75.9,
      description: "Cloudy",
      windSpeed: 4.6,
      windDirection: 89,
    },
    betting: {
      spread: 2.5,
      overUnder: 42.5,
      homeMoneyline: 180,
      awayMoneyline: -220,
    },
  },
  {
    id: 401762469,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: "CBSSN",
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Michie Stadium",
      city: "West Point",
      state: "NY",
    },
    homeTeam: {
      id: 349,
      name: "Army Black Knights",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 249,
      name: "North Texas Mean Green",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 60.1,
      description: null,
      windSpeed: 0.9,
      windDirection: 200,
    },
    betting: {
      spread: 2,
      overUnder: 52,
      homeMoneyline: -110,
      awayMoneyline: -110,
    },
  },
  {
    id: 401762470,
    startDate: "2025-09-20T16:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Raymond James Stadium",
      city: "Tampa",
      state: "FL",
    },
    homeTeam: {
      id: 58,
      name: "South Florida Bulls",
      conference: "American Athletic",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2569,
      name: "South Carolina State Bulldogs",
      conference: "MEAC",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 86.5,
      description: null,
      windSpeed: 8.1,
      windDirection: 59,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401762820,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: true,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Waldo Stadium",
      city: "Kalamazoo",
      state: "MI",
    },
    homeTeam: {
      id: 2711,
      name: "Western Michigan Broncos",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2649,
      name: "Toledo Rockets",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 63.3,
      description: null,
      windSpeed: 2,
      windDirection: 156,
    },
    betting: {
      spread: 14,
      overUnder: 51,
      homeMoneyline: 430,
      awayMoneyline: -625,
    },
  },
  {
    id: 401762821,
    startDate: "2025-09-20T22:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "InfoCision Stadium",
      city: "Akron",
      state: "OH",
    },
    homeTeam: {
      id: 2006,
      name: "Akron Zips",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2184,
      name: "Duquesne Dukes",
      conference: "NEC",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 65.3,
      description: null,
      windSpeed: 6.3,
      windDirection: 144,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401762822,
    startDate: "2025-09-20T17:00:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Kelly/Shorts Stadium",
      city: "Mount Pleasant",
      state: "MI",
    },
    homeTeam: {
      id: 2117,
      name: "Central Michigan Chippewas",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2681,
      name: "Wagner Seahawks",
      conference: "NEC",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 61.3,
      description: null,
      windSpeed: 4.9,
      windDirection: 298,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
  {
    id: 401762823,
    startDate: "2025-09-20T19:30:00.000Z",
    startTimeTBD: false,
    tv: null,
    neutralSite: false,
    conferenceGame: false,
    status: "scheduled",
    period: null,
    clock: null,
    situation: null,
    possession: null,
    lastPlay: null,
    venue: {
      name: "Peden Stadium",
      city: "Athens",
      state: "OH",
    },
    homeTeam: {
      id: 195,
      name: "Ohio Bobcats",
      conference: "Mid-American",
      classification: "fbs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    awayTeam: {
      id: 2241,
      name: "Gardner-Webb Runnin' Bulldogs",
      conference: "Big South-OVC",
      classification: "fcs",
      points: null,
      lineScores: null,
      winProbability: null,
    },
    weather: {
      temperature: 79,
      description: null,
      windSpeed: 2.9,
      windDirection: 211,
    },
    betting: {
      spread: null,
      overUnder: null,
      homeMoneyline: null,
      awayMoneyline: null,
    },
  },
];
export default scoreboad;
